#+TITLE: Output file format
#+AUTHOR: sergisi, quimpm

* Gramàtica:
\begin{verbatim}
mover libro = id libro, "m", id biblioteca
leer libro = id libro, "r", id lector
\end{verbatim}

El orden de sentencias en el fichero importa.
Por ejemplo, dado el fichero inicial:

\begin{verbatim}
T 10
L 0 0
B 0 0 5
B 1 0 5
B 2 0 5
B 3 0 5
R 0 0 0 5 1 5 2 5 3 10
\end{verbatim}

Con el output:
\begin{verbatim}
0 r 0
1 r 0
2 r 0
3 r 0
\end{verbatim}
Generará un valor de 15 puntos, pues el ultimo
libro se lee fuera del timepo establecido (10).
Este se leerá a partir del dia 5 (empezando en 0),
pues los 5 primeros esta ya leiendo 3 libros.

Mientras, este fichero:
\begin{verbatim}
0 r 0
3 r 0
1 r 0
2 r 0
\end{verbatim}
Generará 20 puntos, pues todos los libros son leidos
en el terminio.

Sigamos con otro ejemplo:
\begin{verbatim}
T 10
L 0 0
B 0 0 5
B 1 0 5
B 2 0 5
B 3 0 5
B 4 0 5
R 0 0 0 5 1 5 2 5 3 10 4 3
R 1 0 4 3
\end{verbatim}

Entonces, este fichero:
\begin{verbatim}
0 r 0
1 r 0
2 r 0
4 r 0
4 r 1
\end{verbatim}
Generará 15 puntos, ya que:
1) El lector 0 tiene los 5 primeros dias ocupados.
2) El libro 4 está hasta el octavo dia ocupado, los
   5 primeros sin hacer nada, y del $[5, 8)$ esta
   siendo leido por el lector 1
3) El libro 4 se empieza a leer del 8o dia hasta el 11o.

Mientras, el siguiente output:
\begin{verbatim}
0 r 0
1 r 0
2 r 0
4 r 1
4 r 0
\end{verbatim}
Generará 20 puntos, pues el libro 4 es leido por dos
lectores.
