from .Parser import Parser
from collections import namedtuple

"""
    namedtuple to store the book values that we read from the benchmark.
    @param id: id of the book
    @param value: number representing the value generated by reading the book
    @param id_library: number of the library in wich belongs
"""
Book = namedtuple('Book', ['id', 'value', 'id_library'])

class BookParser(Parser):

    """
    Creates a book from a line of the benchmark
    @param line: string with a line of the benchmark file
    """
    def parse(self, line):
        values = line.split()
        return Book(int(values[1]), int(values[2]), int(values[3]))

